#MossCheckTicket配置文件
#Design By MossCG

#前言
#当你确认配置没问题后，请将以下选项修改为true后再启动喵
enable: true

#----------------------------------
#票务信息
#热门项目：
#Bilibili world 2024 : 85939
#Bilibili macro link 2024 : 85938

#展演ID
showID: "85939"

#----------------------------------
#邮件功能信息
#有票会有邮件提醒
#请自行部署EasyMail（https://github.com/AutoTicketBilibili/EasyMail）
enableMail: false
#EasyMail地址及端口
mailAddress: "127.0.0.1:7654"
#EasyMail配置的token
mailToken: "1234567890"

#----------------------------------
#是否显示调试信息
debug: true
